version: "3.8"

services:
  backend:
    image: mohsenfennnira/newtechmindbackend:latest
    container_name: springboot_container
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/newTechMindDataBase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newTechMindDataBase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
volumes:
  mysql_data:
# Documentation:
# 1. Ensure Docker and Docker Compose are installed on your system.
# 2. Save this file as 'docker-compose.yml'.
# 3. Open a terminal and navigate to the directory containing this file.
# 4. Run the following command to start the services:
#    docker-compose up -d
# 5. To check running containers, use:
#    docker ps
# 6. Access the backend API at:
#    http://localhost:8085
# 7. Access MySQL on port 3306 using any MySQL client.
# 8. Access phpMyAdmin at:
#    http://localhost:8081
# 9. To stop the services, run:
#    docker-compose down
